### ISSUE TITLE
Error after uploading and using search.php

### ISSUE THREAD

**Issue by kreativmind** [anaggh/Bludit-Search#1] opened 2016-09-29 01:54 UTC
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /mysite.com/search.php:35) in /bl-kernel/helpers/session.class.php on line 40

**Comment by anaggh** [comment] 2016-11-21 15:59
Unable to reproduce this. Closing this.

**Closed by anaggh** 2016-11-21 15:59 UTC
Labels: help wanted
